# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a4690107b3a984c3fc54785156a46fc794a0b9da0dc429f1a27d75a43151be13fac7e5128cfc5f894624d5576e0096c4d5413047cce999afb91a08e237e3c3

test:
  secret_key_base: 9134b3014cbb5535199abc70989092f4ed2ec93acdc18ae577d868e4e60964c920dd6ecabeabad3e0136ab2c3b2044d218211566c3bd3a26c4813351bba137d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
